# This file was generated by GoReleaser. DO NOT EDIT.
cask "focci" do
  depends_on macos: true

  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "8fded7c835f02de70aaff731418fe094eaa6a7885eceb5a22b60d774df307bcd"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "118d172f04c4f321dab2ba341c0f9082eb0b6f67b28076686f3a829707e5622b"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "focci"
  desc "Refocus your terminal/editor when an AI coding agent needs your attention"
  homepage "https://github.com/HabibUllahKhanBarakzai/focci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "focci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/focci"]
    end
  end

  # No zap stanza required

end
