# This file was generated by GoReleaser. DO NOT EDIT.
cask "focci" do
  depends_on macos: ">= :big_sur"

  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "bad218f20691cf5e0fb3c91be42d0d831ed892cd7fb2539953d312213f833b31"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "62ba8eaccf87a5d7ad7f0858162c52af9aed17ec713e91676127ab4f99f98f14"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "focci"
  desc "Refocus your terminal/editor when an AI coding agent needs your attention"
  homepage "https://github.com/HabibUllahKhanBarakzai/focci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "focci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/focci"]
    end
  end

  # No zap stanza required

end
