# This file was generated by GoReleaser. DO NOT EDIT.
cask "focci" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "b1a301532996d003711ab98f5c676306f92c8e27d022b5dffe729a8475d01375"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "03cdb35b1081b0544779ec2abedfe6652d0153bb4d5cc2304c73bd5eb887f2bf"
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "focci"
  desc "Refocus your terminal/editor when an AI coding agent needs your attention"
  homepage "https://github.com/HabibUllahKhanBarakzai/focci"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "focci"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/focci"]
    end
  end

  # No zap stanza required

end
