# This file was generated by the focci release workflow. DO NOT EDIT.
class Focci < Formula
  desc "Refocus your terminal/editor when an AI coding agent needs your attention"
  homepage "https://github.com/HabibUllahKhanBarakzai/focci"
  license "Apache-2.0"
  version "0.3.3"

  on_macos do
    on_arm do
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_arm64.tar.gz"
      sha256 "2802c0a4c1b86d013d46436acfe45c82c7c23f73bd285f4948865153f5f6f851"
    end

    on_intel do
      url "https://github.com/HabibUllahKhanBarakzai/focci/releases/download/v#{version}/focci_#{version}_darwin_amd64.tar.gz"
      sha256 "a4d887cddb74c02bd3956e37d10aad3793d1e32c74ac0fe15f593b3333552f49"
    end
  end

  depends_on macos: :big_sur

  def install
    bin.install "focci"
  end

  test do
    assert_match "focci #{version}", shell_output("#{bin}/focci --version")
  end
end
